# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from __future__ import annotations

import argparse
from collections import defaultdict
import json
from math import sqrt
from pathlib import Path
import re
from statistics import mean
from typing import Any

from ._viewer_common import (
    assistant_text,
    decode_image_data_url,
    first_input_image_url,
    input_text,
    read_jsonl,
)

THINK_RE = re.compile(r"<think>(.*?)</think>", re.DOTALL)

# Doc 2 R7: kept in sync with `string_match.BOXED_PATTERN` and
# `text_action_agent.BOXED_PATTERN`. If string_match's pattern changes,
# update all three together (grep for r"\\boxed\\{").
BOXED_PATTERN = re.compile(r"\\boxed\{\s*(.*?)\s*\}", re.S)


class RolloutInspectionError(ValueError):
    """Raised when trajectory_collection.jsonl violates the inspector contract."""


def _std(values: list[float]) -> float:
    if not values:
        return 0.0
    mu = mean(values)
    return sqrt(sum((value - mu) ** 2 for value in values) / len(values))


def _fraction(numerator: int, denominator: int) -> float | None:
    if denominator == 0:
        return None
    return numerator / denominator


def _parse_rollout_line(row: dict[str, Any]) -> dict[str, Any]:
    if "full_result" not in row:
        return row
    full_result = row["full_result"]
    if isinstance(full_result, str):
        return json.loads(full_result)
    if isinstance(full_result, dict):
        return full_result
    raise RolloutInspectionError("full_result must be a JSON string or object")


def load_rollouts(path: str | Path) -> list[dict[str, Any]]:
    return [_parse_rollout_line(row) for row in read_jsonl(path)]


def load_row_source(path: str | Path | None) -> dict[str, dict[str, Any]]:
    if path is None:
        return {}
    rows = read_jsonl(path)
    lookup: dict[str, dict[str, Any]] = {}
    for idx, row in enumerate(rows):
        if row.get("task_id") is not None:
            lookup[str(row["task_id"])] = row
        if row.get("env_id") is not None:
            lookup.setdefault(str(row["env_id"]), row)
        lookup[str(idx)] = row
    return lookup


def _validate_flat_output(row: dict[str, Any]) -> None:
    if row.get("contains_transitions") is True:
        raise RolloutInspectionError(
            "Nested transition history detected (contains_transitions=true). "
            "Set AviaryAgent.return_transitions=false for trajectory collection."
        )
    output = row.get("output", [])
    if output and isinstance(output[0], list):
        raise RolloutInspectionError(
            "Nested transition output detected. Set AviaryAgent.return_transitions=false."
        )


def _env_id(row: dict[str, Any], row_source: dict[str, dict[str, Any]]) -> str:
    # Direct hit (legacy standalone-collection format).
    if row.get("env_id") and str(row["env_id"]) in row_source:
        return str(row_source[str(row["env_id"])].get("env_id", row["env_id"]))
    if row.get("env_id"):
        return str(row["env_id"])
    # NeMo-Gym format: per-rollout response carries `group_id` (which equals
    # the JSONL `task_idx` of the source row) and `env_id` (a per-rollout
    # session UUID generated by gym_v server, NOT the gymnasium env name).
    # The meaningful env name (e.g. "Games/FrozenLake-v0") only lives in the
    # task-source JSONL, so we resolve via group_id → task_idx → row_source.
    response = row.get("response") if isinstance(row.get("response"), dict) else {}
    response_group_id = response.get("group_id")
    if response_group_id is not None and str(response_group_id) in row_source:
        return str(row_source[str(response_group_id)]["env_id"])
    for key in ("task_id", "group_id", "_ng_task_index", "task_idx"):
        if row.get(key) is not None and str(row[key]) in row_source:
            return str(row_source[str(row[key])]["env_id"])
    return "unknown"


def _row_metadata(row: dict[str, Any], row_source: dict[str, dict[str, Any]]) -> dict[str, Any]:
    # NeMo-Gym format: response.group_id == JSONL task_idx (the row index).
    response = row.get("response") if isinstance(row.get("response"), dict) else {}
    response_group_id = response.get("group_id")
    if response_group_id is not None and str(response_group_id) in row_source:
        return row_source[str(response_group_id)]
    for key in ("task_id", "group_id", "_ng_task_index", "task_idx"):
        if row.get(key) is not None and str(row[key]) in row_source:
            return row_source[str(row[key])]
    if row.get("env_id") is not None and str(row["env_id"]) in row_source:
        return row_source[str(row["env_id"])]
    return {}


def _first_boxed_answer(output: list[dict[str, Any]]) -> tuple[bool, str | None]:
    """Return (any-boxed-match-found, last-boxed-answer) across all assistant
    text in the rollout. Lenient by design: this scans the entire rollout
    and returns the last `\\boxed{...}` capture anywhere, mirroring how
    Path B action extraction works in `text_action_agent`. Per-rollout
    `format_match` (the legacy Doc 1 column) uses this; Doc 2's strict
    decision criterion uses the per-turn variant in
    `_per_turn_executable_action`.
    """
    text_parts: list[str] = []
    for item in output:
        if item.get("role") != "assistant":
            continue
        text_parts.append(assistant_text(item))
    text = "\n".join(text_parts)
    matches = BOXED_PATTERN.findall(text)
    if not matches:
        return False, None
    answer = matches[-1].strip() or None
    return (answer is not None), answer


def _split_turns(output: list[dict[str, Any]]) -> list[list[dict[str, Any]]]:
    """Group flat output into per-turn assistant blocks.

    A "turn" is the contiguous set of assistant items (assistant messages
    and/or function_calls) emitted by the model in a single round-trip
    against /v1/responses. Turn boundaries are user messages and
    function_call_output items (server-returned obs).

    This produces one element per assistant turn, even if that turn produced
    BOTH an assistant `<think>` message AND an `act` function_call.

    Note: per Doc 2 § Metadata side-channel commitment, the flat transcript
    can contain consecutive assistant messages when the agent recovers from
    a failed turn (successful_transition=False skips appending the recovery
    user message). Two consecutive assistant items therefore count as TWO
    turns, which is the correct semantics for per-turn fmt-match.
    """
    turns: list[list[dict[str, Any]]] = []
    current: list[dict[str, Any]] = []

    def _is_assistant(item: dict[str, Any]) -> bool:
        if item.get("type") == "function_call":
            return True
        if item.get("type") == "message" and item.get("role") == "assistant":
            return True
        return False

    def _is_turn_separator(item: dict[str, Any]) -> bool:
        # User messages (env obs or recovery) and function_call_output items
        # (Aviary-style tool returns) close the current assistant turn.
        if item.get("role") == "user":
            return True
        if item.get("type") == "function_call_output":
            return True
        return False

    for item in output:
        if _is_assistant(item):
            # Consecutive-assistant case (Doc 2 § Metadata side-channel
            # commitment): if the agent emits a recovery without an
            # intervening user message, the flat transcript can contain two
            # back-to-back assistant *messages*. The second message starts a
            # new turn — that's the `any(c.get("type") == "message" ...)`
            # branch below.
            if (
                current
                and item.get("type") == "message"
                and any(c.get("type") == "message" for c in current)
            ):
                turns.append(current)
                current = []
            current.append(item)
        elif _is_turn_separator(item):
            if current:
                turns.append(current)
                current = []
        # Non-assistant non-separator items (e.g., reasoning items) attach to
        # the current turn implicitly by being ignored here.

    if current:
        turns.append(current)
    return turns


def _per_turn_executable_action(
    turn: list[dict[str, Any]],
    *,
    grammar_regex: str | None,
) -> tuple[bool, bool | None]:
    """Return (per_turn_fmt_match, per_turn_vocab_in_set) for one turn.

    Path B only: scan the turn's assistant text for the LAST `\\boxed{...}`
    capture, and check it against `grammar_regex`. `per_turn_vocab_in_set`
    is None when fmt_match is False or grammar_regex is missing — matching
    the per-rollout `vocab_in_set` semantics.
    """
    text = "\n".join(
        assistant_text(item) for item in turn if item.get("role") == "assistant"
    )
    matches = BOXED_PATTERN.findall(text)
    answer = matches[-1].strip() if matches else ""
    fmt_match = bool(answer)

    if not fmt_match or not grammar_regex:
        return fmt_match, None
    return fmt_match, re.fullmatch(grammar_regex, answer) is not None


def _extract_think_chars(output: list[dict[str, Any]]) -> int:
    total = 0
    for item in output:
        if item.get("role") != "assistant":
            continue
        text = assistant_text(item)
        for match in THINK_RE.finditer(text):
            total += len(match.group(1))
    return total


def _generation_tokens(row: dict[str, Any], output: list[dict[str, Any]]) -> int:
    usage = row.get("usage")
    if isinstance(usage, dict) and isinstance(usage.get("output_tokens"), int):
        return usage["output_tokens"]

    total = 0
    for item in output:
        token_ids = item.get("generation_token_ids")
        if isinstance(token_ids, list):
            total += len(token_ids)
    return total


def _turn_count(output: list[dict[str, Any]]) -> int:
    """Count assistant turns. Path B turns produce assistant text containing
    the `\\boxed{...}` action; consecutive-assistant recovery turns each
    count separately (per Doc 2)."""
    return len(_split_turns(output))


def _step_exception_count(output: list[dict[str, Any]]) -> int:
    count = 0
    for item in output:
        if item.get("role") != "user":
            continue
        env_info = item.get("env_info")
        if isinstance(env_info, dict) and env_info.get("env_step_exception"):
            count += 1
    return count


def _horizon_terminated(row: dict[str, Any], output: list[dict[str, Any]]) -> bool:
    if row.get("horizon_terminated") is True:
        return True
    for item in output:
        env_info = item.get("env_info")
        if isinstance(env_info, dict) and env_info.get("horizon_terminated"):
            return True
    return False


def summarize_rollout(
    row: dict[str, Any], row_source: dict[str, dict[str, Any]]
) -> dict[str, Any]:
    # NeMo-Gym's trajectory_collection.jsonl wraps each rollout's response
    # under {"response": {...}, "reward": ...}. Older standalone-collection
    # JSONLs flatten the response into the row top-level. Tolerate both.
    response_view = row
    if isinstance(row.get("response"), dict) and "output" in row["response"]:
        response_view = row["response"]
    _validate_flat_output(response_view)
    output = response_view.get("output") or []
    env_id = _env_id(row, row_source)
    task_row = _row_metadata(row, row_source)
    regex = row.get("act_grammar_regex") or task_row.get("act_grammar_regex")

    # Path B only: rollouts are scored by their last `\boxed{...}` capture.
    format_match, answer = _first_boxed_answer(output)
    vocab_in_set: bool | None = None
    if format_match and regex:
        vocab_in_set = re.fullmatch(regex, answer or "") is not None

    turn_blocks = _split_turns(output)
    turns = len(turn_blocks)

    # Per-turn breakdown (Doc 2 § Action-format and action-vocabulary metrics).
    per_turn_fmt_matches = []
    per_turn_vocab_matches = []  # only counted when fmt_match was True
    for turn in turn_blocks:
        fmt, vocab = _per_turn_executable_action(turn, grammar_regex=regex)
        per_turn_fmt_matches.append(fmt)
        if fmt and vocab is not None:
            per_turn_vocab_matches.append(vocab)

    step_exceptions = _step_exception_count(output)

    # `id`/`group_id` may live on the row top-level (legacy) or under
    # response (NeMo-Gym format); reward is always on the row top-level.
    rollout_id = row.get("id") or response_view.get("id")
    group_id = (
        row.get("group_id")
        or response_view.get("group_id")
        or row.get("_ng_task_index")
        or ""
    )
    # seed_obs is the initial observation from /seed_session, stored
    # separately from output per Option B (seed-obs-persistence-problem.md).
    seed_obs = response_view.get("seed_obs") or []

    return {
        "id": rollout_id,
        "env_id": env_id,
        "group_id": str(group_id),
        "reward": float(row.get("reward", 0.0)),
        "any_success": float(row.get("reward", 0.0)) > 0.0,
        "think_chars": _extract_think_chars(output),
        "generation_tokens": _generation_tokens(row, output),
        "turns": turns,
        "format_match": format_match,
        "vocab_in_set": vocab_in_set,
        "per_turn_fmt_matches": per_turn_fmt_matches,
        "per_turn_vocab_matches": per_turn_vocab_matches,
        "horizon_terminated": _horizon_terminated(row, output),
        "context_length_exceeded": bool(row.get("context_length_exceeded", False)),
        "step_exceptions": step_exceptions,
        "step_exception_rate": _fraction(step_exceptions, turns),
        "answer": answer,
        "seed_obs": seed_obs,
        "output": output,
        "task_row": task_row,
    }


def _per_env_report(summaries: list[dict[str, Any]]) -> dict[str, Any]:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for summary in summaries:
        grouped[summary["env_id"]].append(summary)

    report: dict[str, Any] = {}
    for env_id, rows in sorted(grouped.items()):
        rewards = [row["reward"] for row in rows]
        vocab_rows = [row for row in rows if row["vocab_in_set"] is not None]
        total_turns = sum(row["turns"] for row in rows)
        total_step_exc = sum(row["step_exceptions"] for row in rows)

        # Per-turn aggregation (Doc 2 § Action-format and action-vocabulary
        # metrics): the decision criterion's primary metric is computed across
        # ALL assistant turns in ALL rollouts for this env (not per-rollout
        # binary).
        all_turn_fmt = [
            fmt for row in rows for fmt in row["per_turn_fmt_matches"]
        ]
        all_turn_vocab = [
            vocab for row in rows for vocab in row["per_turn_vocab_matches"]
        ]
        per_turn_fmt_match = (
            mean([float(v) for v in all_turn_fmt]) if all_turn_fmt else None
        )
        per_turn_vocab_in_set = (
            mean([float(v) for v in all_turn_vocab]) if all_turn_vocab else None
        )
        per_turn_executable_action_rate: float | None
        if per_turn_fmt_match is None or per_turn_vocab_in_set is None:
            per_turn_executable_action_rate = None
        else:
            per_turn_executable_action_rate = (
                per_turn_fmt_match * per_turn_vocab_in_set
            )

        report[env_id] = {
            "n": len(rows),
            "any_success": mean([row["any_success"] for row in rows]),
            "reward_mean": mean(rewards),
            "reward_std": _std(rewards),
            "cot_chars_mean": mean([row["think_chars"] for row in rows]),
            "generation_tokens_mean": mean([row["generation_tokens"] for row in rows]),
            "turns_per_episode_mean": mean([row["turns"] for row in rows]),
            "format_match": mean([row["format_match"] for row in rows]),
            "vocab_in_set": (
                None
                if not vocab_rows
                else mean([bool(row["vocab_in_set"]) for row in vocab_rows])
            ),
            "per_turn_fmt_match": per_turn_fmt_match,
            "per_turn_vocab_in_set": per_turn_vocab_in_set,
            "per_turn_executable_action_rate": per_turn_executable_action_rate,
            "horizon_truncation": mean([row["horizon_terminated"] for row in rows]),
            "context_length_exceeded": mean(
                [row["context_length_exceeded"] for row in rows]
            ),
            "step_exception_rate": _fraction(total_step_exc, total_turns),
        }
    return report


def _per_group_report(summaries: list[dict[str, Any]]) -> dict[str, Any]:
    grouped: dict[tuple[str, str], list[dict[str, Any]]] = defaultdict(list)
    for summary in summaries:
        grouped[(summary["group_id"], summary["env_id"])].append(summary)

    groups: list[dict[str, Any]] = []
    for (group_id, env_id), rows in sorted(grouped.items()):
        rewards = [row["reward"] for row in rows]
        reward_std = _std(rewards)
        groups.append(
            {
                "group_id": group_id,
                "env_id": env_id,
                "n_rollouts": len(rows),
                "reward_mean": mean(rewards),
                "reward_std": reward_std,
                "nonzero_variance": reward_std > 0.0,
                "any_success": any(row["any_success"] for row in rows),
            }
        )

    zero_variance = sum(not group["nonzero_variance"] for group in groups)
    by_env: dict[str, dict[str, Any]] = defaultdict(lambda: {"total": 0, "nonzero": 0})
    for group in groups:
        stats = by_env[group["env_id"]]
        stats["total"] += 1
        stats["nonzero"] += int(group["nonzero_variance"])

    return {
        "groups": groups,
        "filter_rate": _fraction(zero_variance, len(groups)),
        "effective_nonzero_groups_per_step_per_env": {
            env_id: {
                "nonzero": stats["nonzero"],
                "total": stats["total"],
                "fraction": _fraction(stats["nonzero"], stats["total"]),
            }
            for env_id, stats in sorted(by_env.items())
        },
    }


def build_report(
    jsonl_path: str | Path,
    row_source_path: str | Path | None = None,
    env_filter: str | None = None,
) -> dict[str, Any]:
    row_source = load_row_source(row_source_path)
    summaries = [
        summarize_rollout(row, row_source)
        for row in load_rollouts(jsonl_path)
    ]
    if env_filter:
        pattern = re.compile(env_filter.replace("*", ".*"))
        summaries = [row for row in summaries if pattern.fullmatch(row["env_id"])]

    return {
        "per_env": _per_env_report(summaries),
        "per_group": _per_group_report(summaries),
        "rollouts": summaries,
    }


def _safe_env_dir(env_id: str) -> str:
    return env_id.replace("/", "__").replace(":", "_")


def write_sample_rollouts(
    summaries: list[dict[str, Any]], out_dir: Path, top_k: int, bottom_k: int
) -> None:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for summary in summaries:
        grouped[summary["env_id"]].append(summary)

    for env_id, rows in grouped.items():
        env_dir = out_dir / "samples" / _safe_env_dir(env_id)
        env_dir.mkdir(parents=True, exist_ok=True)
        selected = (
            [("best", row) for row in sorted(rows, key=lambda row: row["reward"], reverse=True)[:top_k]]
            + [("worst", row) for row in sorted(rows, key=lambda row: row["reward"])[:bottom_k]]
        )
        for idx, (label, row) in enumerate(selected):
            _write_one_sample(env_dir, label, idx, row)


def _write_one_sample(env_dir: Path, label: str, idx: int, row: dict[str, Any]) -> None:
    md_lines = [
        f"# {label} rollout {idx}",
        "",
        f"- env_id: `{row['env_id']}`",
        f"- reward: `{row['reward']}`",
        f"- group_id: `{row['group_id']}`",
        "",
    ]
    image_idx = 0

    # Render seed_obs first (Option B: initial observation stored separately
    # from output per seed-obs-persistence-problem.md). Older trajectories
    # without seed_obs will have an empty list here and skip this block.
    for item in row.get("seed_obs") or []:
        text = input_text(item) if isinstance(item, dict) else str(item)
        if text:
            md_lines.extend(["## Seed Observation", "", text, ""])
        image_url = first_input_image_url(item) if isinstance(item, dict) else None
        if image_url:
            image_name = f"{label}_{idx}_seed_{image_idx}.png"
            decode_image_data_url(image_url).save(env_dir / image_name)
            md_lines.extend([f"![seed {image_idx}]({image_name})", ""])
            image_idx += 1

    for item in row["output"]:
        if item.get("role") == "assistant":
            md_lines.extend(["## Assistant", "", assistant_text(item), ""])
        elif item.get("role") == "user":
            md_lines.extend(["## User", "", input_text(item), ""])
            image_url = first_input_image_url(item)
            if image_url:
                image_name = f"{label}_{idx}_turn_{image_idx}.png"
                decode_image_data_url(image_url).save(env_dir / image_name)
                md_lines.extend([f"![turn {image_idx}]({image_name})", ""])
                image_idx += 1
        elif item.get("type") == "function_call":
            md_lines.extend(
                [
                    "## Action",
                    "",
                    f"`{item.get('name')}` arguments: `{item.get('arguments')}`",
                    "",
                ]
            )
    (env_dir / f"{label}_{idx}.md").write_text("\n".join(md_lines))


def write_report(report: dict[str, Any], out_dir: str | Path, top_k: int, bottom_k: int) -> None:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "report.json").write_text(
        json.dumps(
            {"per_env": report["per_env"], "per_group": report["per_group"]},
            indent=2,
            sort_keys=True,
        )
    )
    write_sample_rollouts(report["rollouts"], out, top_k=top_k, bottom_k=bottom_k)


def _fmt(value: float | None) -> str:
    if value is None:
        return "unknown"
    return f"{value:.3f}"


def print_report(report: dict[str, Any]) -> None:
    header = (
        "Env                            n   any-success  reward mean  "
        "fmt-match  vocab-in-set  pt-fmt  pt-vocab  pt-exec  step-exc"
    )
    print(header)
    for env_id, row in report["per_env"].items():
        print(
            f"{env_id:<30} {row['n']:<3} {_fmt(row['any_success']):<12} "
            f"{_fmt(row['reward_mean']):<12} {_fmt(row['format_match']):<10} "
            f"{_fmt(row['vocab_in_set']):<13} "
            f"{_fmt(row['per_turn_fmt_match']):<7} "
            f"{_fmt(row['per_turn_vocab_in_set']):<9} "
            f"{_fmt(row['per_turn_executable_action_rate']):<8} "
            f"{_fmt(row['step_exception_rate'])}"
        )
    print()
    print(f"filter_rate: {_fmt(report['per_group']['filter_rate'])}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--jsonl", required=True, help="trajectory_collection.jsonl")
    parser.add_argument("--row-source", default=None, help="Task-row JSONL used by the server")
    parser.add_argument("--out-dir", required=True, help="Directory for report.json and samples/")
    parser.add_argument("--env-filter", default=None)
    parser.add_argument("--top-k", type=int, default=5)
    parser.add_argument("--bottom-k", type=int, default=5)
    args = parser.parse_args()

    report = build_report(args.jsonl, row_source_path=args.row_source, env_filter=args.env_filter)
    write_report(report, args.out_dir, top_k=args.top_k, bottom_k=args.bottom_k)
    print_report(report)


if __name__ == "__main__":
    main()
