harbor_agent:
  responses_api_agents:
    harbor_agent:
      entrypoint: app.py
      concurrency: 50

      harbor_datasets:
        terminal_bench:
          dataset_name: "terminal-bench"
          dataset_version: "2.0"

      harbor_agent_name: null
      harbor_agent_import_path: "responses_api_agents.harbor_agent.custom_agents.droid_nemo_gym:DroidNemoGym"

      harbor_agent_kwargs:
        api_base: ${policy_base_url}
        api_key: ${policy_api_key}
        max_output_tokens: 32768
        max_context_limit: 131072

      harbor_environment_type: "docker"
      harbor_environment_kwargs: {}

      model_server:
        type: responses_api_models
        name: policy_model

      harbor_agent_override_timeout: 1800
      harbor_jobs_dir: "jobs"
